const {SlashCommandBuilder,PermissionFlagsBits,ChannelType}=require('discord.js');
const commands=[
 new SlashCommandBuilder().setName('help').setDescription('Show Anime Cloud commands'),
 new SlashCommandBuilder().setName('ping').setDescription('Check bot latency'),
 new SlashCommandBuilder().setName('plans').setDescription('Show Anime Cloud plans').addStringOption(o=>o.setName('category').setDescription('Plan category').addChoices({name:'All Plans',value:'all'},{name:'IPv4 Services',value:'ipv4'},{name:'Minecraft India',value:'minecraft'},{name:'Paid VPS',value:'vps'})),
 new SlashCommandBuilder().setName('status').setDescription('Show Anime Cloud service status'),
 new SlashCommandBuilder().setName('profile').setDescription('Show your customer profile'),
 new SlashCommandBuilder().setName('orders').setDescription('Show all orders').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild),
 new SlashCommandBuilder().setName('order').setDescription('Create an Anime Cloud order').addStringOption(o=>o.setName('plan').setDescription('Plan name').setRequired(true)).addStringOption(o=>o.setName('note').setDescription('Optional note')),
 new SlashCommandBuilder().setName('pay').setDescription('Pay an order with UPI QR').addStringOption(o=>o.setName('order_id').setDescription('Order ID').setRequired(true)).addStringOption(o=>o.setName('transaction_id').setDescription('UPI transaction ID after payment')),
 new SlashCommandBuilder().setName('qrcode').setDescription('Generate a public UPI QR').addNumberOption(o=>o.setName('amount').setDescription('Amount INR').setMinValue(1).setMaxValue(1000000).setRequired(true)).addStringOption(o=>o.setName('reference').setDescription('Payment reference')),
 new SlashCommandBuilder().setName('coupon').setDescription('Check a coupon').addStringOption(o=>o.setName('code').setDescription('Coupon code').setRequired(true)),
 new SlashCommandBuilder().setName('ticket').setDescription('Open a support ticket').addStringOption(o=>o.setName('category').setDescription('Support category').addChoices({name:'Billing',value:'billing'},{name:'VPS Support',value:'vps'},{name:'Minecraft',value:'minecraft'},{name:'IPv4',value:'ipv4'},{name:'Technical',value:'technical'},{name:'General',value:'general'})),
 new SlashCommandBuilder().setName('ticket-panel').setDescription('Post category-based ticket panel').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addChannelOption(o=>o.setName('channel').setDescription('Panel channel').addChannelTypes(ChannelType.GuildText)),
 new SlashCommandBuilder().setName('invoice').setDescription('Create PNG + PDF invoice').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addStringOption(o=>o.setName('customer').setDescription('Customer').setRequired(true)).addStringOption(o=>o.setName('items').setDescription('Name=Price, Name=Price').setRequired(true)).addStringOption(o=>o.setName('time').setDescription('Validity').setRequired(true)).addStringOption(o=>o.setName('status').setDescription('Status').addChoices({name:'PAID',value:'PAID'},{name:'PENDING',value:'PENDING'})),
 new SlashCommandBuilder().setName('dm').setDescription('Send a customer DM').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addUserOption(o=>o.setName('user').setDescription('Customer').setRequired(true)).addStringOption(o=>o.setName('message').setDescription('Message').setRequired(true)),
 new SlashCommandBuilder().setName('announcement').setDescription('Send an announcement').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addStringOption(o=>o.setName('title').setDescription('Title').setRequired(true)).addStringOption(o=>o.setName('message').setDescription('Message').setRequired(true)).addChannelOption(o=>o.setName('channel').setDescription('Channel').setRequired(true)).addBooleanOption(o=>o.setName('everyone').setDescription('Mention @everyone')),
 new SlashCommandBuilder().setName('panel').setDescription('Create an Anime Cloud panel').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addSubcommand(s=>s.setName('payment').setDescription('Payment panel')).addSubcommand(s=>s.setName('plans').setDescription('Plans panel')).addSubcommand(s=>s.setName('orders').setDescription('Orders panel')).addSubcommand(s=>s.setName('ticket').setDescription('Ticket panel')),
 new SlashCommandBuilder().setName('order-channel').setDescription('Configure order log channel').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addSubcommand(s=>s.setName('setup').setDescription('Set channel').addChannelOption(o=>o.setName('channel').setDescription('Channel').setRequired(true))).addSubcommand(s=>s.setName('disable').setDescription('Disable')),
 new SlashCommandBuilder().setName('welcome').setDescription('Configure welcome messages').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addSubcommand(s=>s.setName('setup').setDescription('Set channel').addChannelOption(o=>o.setName('channel').setDescription('Channel').setRequired(true))).addSubcommand(s=>s.setName('disable').setDescription('Disable')),
 new SlashCommandBuilder().setName('warn').setDescription('Warn a member').setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers).addUserOption(o=>o.setName('user').setDescription('Member').setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Reason').setRequired(true)),
 new SlashCommandBuilder().setName('purge').setDescription('Delete messages').setDefaultMemberPermissions(PermissionFlagsBits.ManageMessages).addIntegerOption(o=>o.setName('amount').setDescription('1-100').setMinValue(1).setMaxValue(100).setRequired(true)),
 new SlashCommandBuilder().setName('admin').setDescription('Anime Cloud administration').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addSubcommand(s=>s.setName('stats').setDescription('Statistics')).addSubcommand(s=>s.setName('coupon').setDescription('Create coupon').addStringOption(o=>o.setName('code').setDescription('Code').setRequired(true)).addIntegerOption(o=>o.setName('percent').setDescription('Discount').setMinValue(1).setMaxValue(100).setRequired(true))).addSubcommand(s=>s.setName('plan-add').setDescription('Add custom plan').addStringOption(o=>o.setName('name').setDescription('Name').setRequired(true)).addIntegerOption(o=>o.setName('ram').setDescription('RAM GB').setMinValue(1).setRequired(true)).addIntegerOption(o=>o.setName('storage').setDescription('NVMe GB').setMinValue(1).setRequired(true)).addIntegerOption(o=>o.setName('cpu').setDescription('vCPU').setMinValue(1).setRequired(true)).addIntegerOption(o=>o.setName('price').setDescription('INR/month').setMinValue(0).setRequired(true))).addSubcommand(s=>s.setName('plan-edit').setDescription('Edit custom plan').addStringOption(o=>o.setName('name').setDescription('Name').setRequired(true)).addIntegerOption(o=>o.setName('ram').setDescription('RAM GB')).addIntegerOption(o=>o.setName('storage').setDescription('NVMe GB')).addIntegerOption(o=>o.setName('cpu').setDescription('vCPU')).addIntegerOption(o=>o.setName('price').setDescription('INR/month'))).addSubcommand(s=>s.setName('plan-delete').setDescription('Delete custom plan').addStringOption(o=>o.setName('name').setDescription('Name').setRequired(true))).addSubcommand(s=>s.setName('plan-list').setDescription('List custom plans')).addSubcommand(s=>s.setName('payment').setDescription('Approve/reject payment').addStringOption(o=>o.setName('payment_id').setDescription('Payment ID').setRequired(true)).addStringOption(o=>o.setName('action').setDescription('Action').setRequired(true).addChoices({name:'APPROVE',value:'approve'},{name:'REJECT',value:'reject'})))
].map(x=>x.toJSON());module.exports=commands;
