const { SlashCommandBuilder, PermissionFlagsBits, ChannelType } = require('discord.js');
const commands = [
 new SlashCommandBuilder().setName('help').setDescription('Show Anime Cloud commands'),
 new SlashCommandBuilder().setName('ping').setDescription('Check bot latency'),
 new SlashCommandBuilder().setName('plans').setDescription('Show Anime Cloud plans').addStringOption(o=>o.setName('category').setDescription('Plan category').addChoices({name:'All Plans',value:'all'},{name:'IPv4 Services',value:'ipv4'},{name:'Minecraft India',value:'minecraft'},{name:'Paid VPS',value:'vps'})),
 new SlashCommandBuilder().setName('status').setDescription('Show bot status'),
 new SlashCommandBuilder().setName('profile').setDescription('Show your profile'),
 new SlashCommandBuilder().setName('orders').setDescription('Show all orders').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild),
 new SlashCommandBuilder().setName('order').setDescription('Create an order').addStringOption(o=>o.setName('plan').setDescription('Plan ID or name').setRequired(true)).addStringOption(o=>o.setName('note').setDescription('Optional note')),
 new SlashCommandBuilder().setName('pay').setDescription('Pay an order with UPI QR').addStringOption(o=>o.setName('order_id').setDescription('Order ID').setRequired(true)).addStringOption(o=>o.setName('transaction_id').setDescription('UPI transaction ID after payment')),
 new SlashCommandBuilder().setName('qrcode').setDescription('Generate a UPI QR').addNumberOption(o=>o.setName('amount').setDescription('INR amount').setMinValue(1).setMaxValue(1000000).setRequired(true)).addStringOption(o=>o.setName('reference').setDescription('Payment reference')),
 new SlashCommandBuilder().setName('coupon').setDescription('Check a coupon').addStringOption(o=>o.setName('code').setDescription('Coupon code').setRequired(true)),
 new SlashCommandBuilder().setName('ticket').setDescription('Open a support ticket'),
 new SlashCommandBuilder().setName('ticket-panel').setDescription('Post category ticket panel').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addChannelOption(o=>o.setName('channel').setDescription('Panel channel').addChannelTypes(ChannelType.GuildText)),
 new SlashCommandBuilder().setName('invoice').setDescription('Create invoice').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addStringOption(o=>o.setName('customer').setDescription('Customer').setRequired(true)).addStringOption(o=>o.setName('items').setDescription('Name=Price, Name=Price').setRequired(true)).addStringOption(o=>o.setName('time').setDescription('Validity').setRequired(true)),
 new SlashCommandBuilder().setName('dm').setDescription('DM a user').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addUserOption(o=>o.setName('user').setDescription('User').setRequired(true)).addStringOption(o=>o.setName('message').setDescription('Message').setRequired(true)),
 new SlashCommandBuilder().setName('announcement').setDescription('Send announcement').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addStringOption(o=>o.setName('title').setDescription('Title').setRequired(true)).addStringOption(o=>o.setName('message').setDescription('Message').setRequired(true)).addChannelOption(o=>o.setName('channel').setDescription('Channel').setRequired(true)),
 new SlashCommandBuilder().setName('panel').setDescription('Post an Anime Cloud panel').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addSubcommand(s=>s.setName('payment').setDescription('Payment panel')).addSubcommand(s=>s.setName('ticket').setDescription('Ticket panel')).addSubcommand(s=>s.setName('plans').setDescription('Plans panel')).addSubcommand(s=>s.setName('orders').setDescription('Orders panel')),
 new SlashCommandBuilder().setName('order-channel').setDescription('Configure order channel').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addSubcommand(s=>s.setName('setup').setDescription('Set channel').addChannelOption(o=>o.setName('channel').setDescription('Channel').setRequired(true))).addSubcommand(s=>s.setName('disable').setDescription('Disable')),
 new SlashCommandBuilder().setName('welcome').setDescription('Configure welcome').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addSubcommand(s=>s.setName('setup').setDescription('Set channel').addChannelOption(o=>o.setName('channel').setDescription('Channel').setRequired(true))).addSubcommand(s=>s.setName('disable').setDescription('Disable')),
 new SlashCommandBuilder().setName('warn').setDescription('Warn member').setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers).addUserOption(o=>o.setName('user').setDescription('Member').setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Reason').setRequired(true)),
 new SlashCommandBuilder().setName('purge').setDescription('Delete messages').setDefaultMemberPermissions(PermissionFlagsBits.ManageMessages).addIntegerOption(o=>o.setName('amount').setDescription('1-100').setMinValue(1).setMaxValue(100).setRequired(true)),
 new SlashCommandBuilder().setName('admin').setDescription('Anime Cloud administration').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addSubcommand(s=>s.setName('stats').setDescription('Statistics')).addSubcommand(s=>s.setName('coupon').setDescription('Create coupon').addStringOption(o=>o.setName('code').setDescription('Code').setRequired(true)).addIntegerOption(o=>o.setName('percent').setDescription('Discount').setMinValue(1).setMaxValue(100).setRequired(true)))
].map(c=>c.toJSON());
module.exports=commands;
